#+Title: Listas de Exercícios
#+Author: Alexandre Rademaker

* Lista 1 

Para <2019-08-13 Tue>. Exercicios 1-5 do [[https://leanprover.github.io/logic_and_proof/natural_deduction_for_propositional_logic.html][capítulo 3]] entregues
pessoalmente.

* Lista 2

Para <2019-08-20 Tue>

1. Exercícios do [[https://leanprover.github.io/logic_and_proof/propositional_logic_in_lean.html][capítulo 4]]. Entrega deve ser um único arquivo lean
   chamado 'capitulo-04-FulanoSilva.lean' onde `Fulano' é o primeiro
   nome e 'Silva' é o último nome. Sem acentos.
2. Completar o problema dos [[vestidos.lean]].

A entrega deve ser feita por email, diretamente para mim, não pela
lista, até as 11h de terça-feira. No assunto da mensagem, colocar: 

   MD 2019.2: lista 2

O email deve conter os dois arquivos lean anexados:

- vestidos-FulanoSilva.lean
- capitulo-04-FulanoSilva.lean

* Lista 3

Para <2019-09-09 Mon> às 10h

1. Prova em Lean do PHP3.
2. Exercícios capítulo 5.
3. Escolher um grafo qq, pequeno, e usando a codificação em lógica
   proposicional, tentar provar no Lean que um dado caminho é mesmo um
   caminho hamiltoniano no grafo.

A entrega deve ser feita por email, diretamente para mim, não pela
lista, até as 11h de <2019-09-05 Thu>. No assunto da mensagem,
colocar:

   *MD 2019.2: lista 3*

O email deve conter os dois arquivos lean anexados:

- PHP-FulanoBeltrano.lean
- capitulo-05-FulanoBeltrano.lean
- HAM-FulanoBeltrano.lean

onde Fulano e Beltrano são os primeiros nomes dos componentes da
dupla. Se o trabalho for feito individualmente, teremos apenas um
nome. Nomes sem acentos. Seguir *rigorosamente* o padrão acima.
